# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 16:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import maps.fields


class Migration(migrations.Migration):

    replaces = [('maps', '0001_initial'), ('maps', '0002_auto_20170114_1951'), ('maps', '0003_country_image'), ('maps', '0004_auto_20170116_1246'), ('maps', '0005_auto_20170118_0509'), ('maps', '0006_country_sparql'), ('maps', '0007_auto_20170118_1452'), ('maps', '0008_auto_20170118_1605'), ('maps', '0009_auto_20170120_1829'), ('maps', '0010_country_is_published'), ('maps', '0011_country_is_global'), ('maps', '0012_area_default_position'), ('maps', '0013_country_default_positions'), ('maps', '0014_remove_area_default_position'), ('maps', '0015_auto_20170218_1628'), ('maps', '0016_country_wikidata_id'), ('maps', '0017_area_wikidata_id'), ('maps', '0018_auto_20170329_1846'), ('maps', '0019_auto_20170329_1848'), ('maps', '0020_remove_area_answer'), ('maps', '0021_area_osm_id'), ('maps', '0022_auto_20170422_1927'), ('maps', '0023_auto_20170423_1023'), ('maps', '0024_region_is_enabled'), ('maps', '0025_auto_20170504_2046'), ('maps', '0026_auto_20170506_1647')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('wikidata_id', maps.fields.ExternalIdField(max_length=20, null=True)),
                ('osm_id', models.PositiveIntegerField(unique=True)),
                ('osm_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Region')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'base_manager_name': '_plain_manager',
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('infobox', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='maps.Region')),
            ],
            options={
                'db_table': 'maps_region_translation',
                'managed': True,
                'abstract': False,
                'default_permissions': (),
                'db_tablespace': '',
            },
        ),
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
