# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_squashed_0026_auto_20170506_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiontranslation',
            options={},
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
            ],
        ),
    ]
