# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='default_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='zoom',
            field=models.PositiveSmallIntegerField(choices=[(3, 'world'), (4, 'large country'), (5, 'big country'), (6, 'country'), (7, 'small country'), (8, 'little country'), (9, 'region')]),
        ),
    ]
