# Generated by Django 2.0.3 on 2018-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170515_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiontranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=15),
        ),
    ]
