# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170114_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, upload_to='countries'),
        ),
    ]
