# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_world'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='answer',
        ),
        migrations.AddField(
            model_name='world',
            name='answer',
            field=django.contrib.gis.db.models.fields.MultiPointField(geography=True, srid=4326, null=True),
        ),
    ]
