# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20170111_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='is_available',
        ),
        migrations.AddField(
            model_name='world',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'easy'), (2, 'normal'), (3, 'hard')], default=0),
        ),
    ]
