# Generated by Django 2.1.2 on 2018-11-04 19:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20180520_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, default='???', max_length=50)),
                ('name_ru', models.CharField(blank=True, default='???', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='osm_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='regiontranslation',
            name='infobox',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
