# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170118_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='sparql',
            field=models.TextField(blank=True, null=True),
        ),
    ]
