# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170112_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='meta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='maps.Meta'),
            preserve_default=False,
        ),
    ]
