# Generated by Django 2.2.2 on 2019-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20190619_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
