# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20170118_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('infobox', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_tablespace': '',
                'default_permissions': (),
                'abstract': False,
                'managed': True,
                'db_table': 'maps_area_translation',
            },
        ),
        migrations.AlterModelManagers(
            name='area',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='areatranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='maps.Area'),
        ),
        migrations.AlterUniqueTogether(
            name='areatranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
