# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20170118_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='infobox',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.AlterField(
            model_name='areatranslation',
            name='infobox',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
