# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20170120_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
