# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_country_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='default_position',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
