# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_area_default_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='default_positions',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, geography=True, srid=4326),
        ),
    ]
