# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_remove_area_default_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries'),
        ),
    ]
