# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20170218_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='wikidata_id',
            field=models.CharField(default='Q27', max_length=15),
            preserve_default=False,
        ),
    ]
