# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_country_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
