# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_area_wikidata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='position',
        ),
        migrations.AlterField(
            model_name='country',
            name='default_positions',
            field=django.contrib.gis.db.models.fields.MultiPointField(geography=True, srid=4326),
        ),
    ]
