# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_auto_20170329_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='default_count',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sparql',
        ),
    ]
