# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_auto_20170329_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='answer',
        ),
    ]
