# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_remove_area_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='osm_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
