# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 19:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_area_osm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('wikidata_id', maps.fields.ExternalIdField(max_length=15)),
                ('osm_id', models.PositiveIntegerField()),
                ('osm_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Region')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('infobox', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='maps.Region')),
            ],
            options={
                'managed': True,
                'db_table': 'maps_region_translation',
                'abstract': False,
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='osm_id',
            field=maps.fields.ExternalIdField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='wikidata_id',
            field=maps.fields.ExternalIdField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='wikidata_id',
            field=maps.fields.ExternalIdField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
