# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 20:46
from __future__ import unicode_literals

from django.db import migrations
import maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_region_is_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterField(
            model_name='region',
            name='wikidata_id',
            field=maps.fields.ExternalIdField(max_length=20, null=True),
        ),
    ]
