# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_auto_20170504_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='areatranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='areatranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='countrytranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='countrytranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='AreaTranslation',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CountryTranslation',
        ),
    ]
