# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171011_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
