# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171012_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=2, null=True),
        ),
    ]
