# Generated by Django 2.2.24 on 2021-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181004_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
