FROM node:20.8.0-bookworm-slim as frontend-builder

WORKDIR /app

RUN apt-get update \
  && apt-get install -y git \
  && apt-get clean

COPY package* ./
RUN npm install --only=prod \
  && npm install --only=dev

ENV NODE_ENV=production

CMD ["node"]
