FROM node:carbon-slim

RUN apt-get update && apt-get install -y git
env NODE_ENV=production
RUN echo $NODE_ENV
COPY package.json /
RUN npm install --only=dev && npm install --only=prod && npm cache clean --force

CMD ["node"]
