FROM node:12-slim as frontend-builder

RUN apt-get update \
  && apt-get install -y git \
  && apt-get clean

COPY package* ./
RUN npm install --only=prod \
  && npm install --only=dev \
  && npm cache clean --force

ENV NODE_ENV=production

CMD ["node"]
