version: '3.7'
services:
  redis:
    image: redis:5-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - webnet

  postgres:
    image: circleci/postgres:12-postgis
    environment:
      POSTGRES_USER: geopuzzle
      POSTGRES_PASSWORD: geopuzzle
      POSTGRES_DB: geopuzzle
    healthcheck:
      test: ["CMD", "pg_isready -U geopuzzle"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  app:
    build:
        context: .
        dockerfile: Dockerfile.backend
        target: backend
    restart: on-failure
    environment:
      DJANGO_SETTINGS_MODULE: mercator.settings.development
      SECRET_KEY: 123

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: geopuzzle
      DB_USER: geopuzzle
      DB_USER_PASSWORD: geopuzzle

      REDIS_HOST: redis
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    networks:
      - webnet
    volumes:
      - .:/app
    command: ./manage.py runserver 0.0.0.0:8000

networks:
  webnet:

volumes:
  pgdata: