# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 19:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('table_name', models.CharField(max_length=15)),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('zoom', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
