# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 16:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    replaces = [('quiz', '0001_initial'), ('quiz', '0002_auto_20170506_0312'), ('quiz', '0003_auto_20170506_0342')]

    initial = True

    dependencies = [
        ('maps', '0025_auto_20170504_2046'),
        ('maps', '0019_auto_20170329_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='puzzles')),
                ('slug', models.CharField(db_index=True, max_length=15)),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('zoom', models.PositiveSmallIntegerField(choices=[(3, 'world'), (4, 'large country'), (5, 'big country'), (6, 'country'), (7, 'small country'), (8, 'little country'), (9, 'region')])),
                ('is_published', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('name', 'name'), ('capital', 'capital'), ('flag', 'flag'), ('coat_of_arms', 'coat_of_arms')], max_length=12), default=['name', 'capital', 'flag', 'coat_of_arms'], size=None)),
                ('regions', models.ManyToManyField(to='maps.Region')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='QuizTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.Quiz')),
            ],
            options={
                'managed': True,
                'default_permissions': (),
                'abstract': False,
                'db_tablespace': '',
                'db_table': 'quiz_quiz_translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='quiztranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
