# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170515_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiztranslation',
            options={},
        ),
        migrations.AlterModelManagers(
            name='quiz',
            managers=[
            ],
        ),
    ]
