# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 03:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170506_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='countries',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('name', 'name'), ('capital', 'capital'), ('flag', 'flag'), ('coat_of_arms', 'coat_of_arms')], max_length=12), default=['name', 'capital', 'flag', 'coat_of_arms'], size=None),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
