# Generated by Django 2.0.3 on 2018-03-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20180311_1734'),
        ('quiz', '0003_auto_20170515_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=15),
        ),
        migrations.RunSQL('ALTER TABLE quiz_quiz_regions RENAME TO quiz_quizregion'),
        migrations.AddField(
            model_name='quizregion',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
