# Generated by Django 2.0.3 on 2018-04-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_user'),
        ('quiz', '0004_auto_20180311_1747'),
    ]

    operations = [
    ]
