# Generated by Django 2.1.2 on 2018-11-04 19:42

import django.contrib.postgres.fields
from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20180509_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('name', 'name'), ('capital', 'capital'), ('flag', 'flag'), ('coat_of_arms', 'coat_of_arms')], max_length=12), default=quiz.models.default_quiz_options, size=None),
        ),
    ]
