# Generated by Django 2.2.8 on 2020-01-06 04:05

from django.db import migrations
import django_enumfield.db.fields
import maps.constants


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20181113_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='zoom',
            field=django_enumfield.db.fields.EnumField(default=6, enum=maps.constants.Zoom),
        ),
    ]
