# Generated by Django 2.2.12 on 2020-04-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200106_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='on_main_page',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
