# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 11:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0024_region_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='puzzles')),
                ('slug', models.CharField(db_index=True, max_length=15)),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('default_positions', django.contrib.gis.db.models.fields.MultiPointField(geography=True, srid=4326)),
                ('zoom', models.PositiveSmallIntegerField(choices=[(3, 'world'), (4, 'large country'), (5, 'big country'), (6, 'country'), (7, 'small country'), (8, 'little country'), (9, 'region')])),
                ('is_published', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('wikidata_id', maps.fields.ExternalIdField(max_length=15)),
                ('regions', models.ManyToManyField(to='maps.Region')),
            ],
            options={
                'verbose_name_plural': 'Puzzles',
                'verbose_name': 'Puzzle',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='puzzle.Puzzle')),
            ],
            options={
                'default_permissions': (),
                'managed': True,
                'db_table': 'puzzle_puzzle_translation',
                'db_tablespace': '',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='puzzletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
