# Generated by Django 2.0.3 on 2018-04-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_puzzle_user'),
        ('puzzle', '0004_auto_20180311_1738'),
    ]

    operations = [
    ]
