# Generated by Django 2.0.3 on 2018-05-09 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0005_merge_20180425_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
