# Generated by Django 2.0.3 on 2018-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_puzzle_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games'),
        ),
        migrations.AlterField(
            model_name='puzzletranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='puzzletranslation',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
