# Generated by Django 2.1.3 on 2018-11-21 07:53

from django.db import migrations, models
import maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0009_auto_20181113_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='regions',
            field=maps.fields.RegionsField(through='puzzle.PuzzleRegion', to='maps.Region'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='maps.Tag'),
        ),
    ]
